# Generated by Django 5.2.1 on 2025-05-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='column',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='board',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
