# Generated by Django 5.2.1 on 2025-05-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_user_board_owner_rename_name_board_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
